language: minimal
os: linux
dist: bionic

install:
  - sudo apt update

script:
  - bin/install_emacs.sh
  - emacs --batch -L lisp -l init.el
  - bin/install_24bit_terminfo.sh
  - bin/install_tmux.sh --ignore-existing
