language: generic

os:
  - linux

install:
  - uname -a
  - sudo apt update

script:
  - bin/install_emacs.sh
  - emacs -nw --eval '(kill-emacs)'
  - bin/install_24bit_terminfo.sh
  - bin/install_tmux.sh --ignore-existing
