language: generic

os:
  - linux

install:
  - uname -a
  - sudo apt update
  - sudo apt purge emacs emacs-nox tmux

script:
  - bin/install_emacs.sh
  - emacs --batch --eval --script init.el
  - bin/install_24bit_terminfo.sh
  - bin/install_tmux.sh --ignore-existing
